server:
  port: 8082

spring:

  # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/goods-service?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    # 数据源/连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    # 数据库驱动名称
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    # 定义初始连接数
    initialSize: 1
    # 定义最小空闲 minIdle=1
    minIdle: 3
    # 定义最大连接数
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 验证使用的SQL语句
    validationQuery: select 'x'
    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    # 借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    # 指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  cloud:
    alibaba:
      # seata事务分组
      seata:
        tx-service-group: goods-service-group

#默认的feign功能中，熔断开关是关闭的，所以，熔断器hystrix的开关需要手动打开
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 50000
        read-timeout: 50000

#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
ribbon:
  ConnectTimeout: 50000
  # 请求处理的超时时间
  ReadTimeout: 50000

# hystrix 熔断机制
hystrix:
  threadpool:
    default:
      coreSize: 100
  command:
    circuitBreaker:
      # 设置熔断器失败的个数
      requestVolumeThreshold: 1000
    default:
      execution:
        # 断路器超时设置
        enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 70000 #缺省为1000
      fallback:
        isolation:
          semaphore:
            # 设置回退的最大线程数
            maxConcurrentRequests: 100

# seata配置
seata:
  enabled:  true
#seata.excludes-for-auto-proxying=firstClassNameForExclude,secondClassNameForExclude
  application-id: goods-service
  tx-service-group: goods-service-group
  enable-auto-data-source-proxy:  true
  registry:
    type:  eureka

  # seata 配置项，对应 serviceProperties 类
  service:
    grouplist:
      seata-server: 192.168.205.120:8091

    # 虚拟为分组映射，key 一定要与tx-service-group相同，
    # value 必须与 seata-server 中file.conf 中 service.vgroupMapping.my_test_tx_group 相同
    vgroup-mapping:
      goods-service-group: seata-server